import fs from "fs";
import path from "path";
import crypto from "crypto";
import { logger } from "./logger";
import { PROJECTS, LIBS, ORIGINAL_FILES } from "./projects";
import { ReplitConnectors } from "@replit/connectors-sdk";

const WORKSPACE = "/home/runner/workspace";
const OWNER = "savinalexandru2002-prog";
const REPO = "Alexandru-";
const PUSH_INTERVAL_MS = 5 * 60 * 1000;

const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  ".cache",
  ".replit-artifact",
  "cloned-repo",
  ".turbo",
  ".vite",
]);
const ALLOWED_EXTS = new Set([
  ".ts", ".js", ".tsx", ".jsx", ".mjs", ".cjs",
  ".json", ".yaml", ".yml", ".toml",
  ".html", ".css", ".scss", ".md", ".txt",
  ".svg", ".webmanifest", ".ico",
  ".py", ".sh", ".sql",
]);

export let lastPushTime: Date | null = null;
export let lastPushResults: { file: string; status: string }[] = [];
export let autoPushEnabled = false;
export let isPushing = false;

// Track content hashes to skip unchanged files
const pushedHashes = new Map<string, string>();

type SyncFile = { path: string; content: Buffer | string };

function hashContent(content: Buffer | string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

function walkDir(dir: string, base: string, results: SyncFile[]) {
  if (!fs.existsSync(dir)) return;
  let entries: fs.Dirent[];
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    const rel = path.posix.join(base, entry.name);
    if (entry.isDirectory()) {
      walkDir(full, rel, results);
    } else {
      if (!ALLOWED_EXTS.has(path.extname(entry.name))) continue;
      try {
        const content = fs.readFileSync(full);
        if (content.length > 0) {
          results.push({ path: rel, content: isTextFile(entry.name) ? content.toString("utf8") : content });
        }
      } catch { /* skip binary */ }
    }
  }
}

function isTextFile(name: string): boolean {
  return ![".ico"].includes(path.extname(name).toLowerCase());
}

function generateProjectReadme(slug: string): string {
  const meta = PROJECTS.find(p => p.slug === slug);
  const name = meta ? `${meta.icon} ${meta.name}` : slug;
  const desc = meta?.description ?? "A Replit project.";
  return [
    `# ${name}`,
    ``,
    `> ${desc}`,
    ``,
    `## About`,
    ``,
    `This project is part of the **Alexandru- Distribution Hub** — automatically synced from Replit every 5 minutes.`,
    ``,
    `## Structure`,
    ``,
    `| Path | Description |`,
    `|------|-------------|`,
    `| \`src/\` | Source code |`,
    `| \`index.html\` | Entry point (if applicable) |`,
    ``,
    `---`,
    `*Auto-generated by GitHub Distribution Hub*`,
  ].join("\n");
}

function generateLibReadme(slug: string): string {
  const meta = LIBS.find(p => p.slug === slug);
  const name = meta ? `${meta.icon} ${meta.name}` : slug;
  const desc = meta?.description ?? "A shared library.";
  return [
    `# ${name}`,
    ``,
    `> ${desc}`,
    ``,
    `## About`,
    ``,
    `This is a shared library used across the **Alexandru- Distribution Hub** projects. Automatically synced from Replit.`,
    ``,
    `---`,
    `*Auto-generated by GitHub Distribution Hub*`,
  ].join("\n");
}

function generateRootReadme(): string {
  // Discover artifacts dynamically
  const artifactsDir = path.join(WORKSPACE, "artifacts");
  const artifactSlugs: string[] = fs.existsSync(artifactsDir)
    ? fs.readdirSync(artifactsDir, { withFileTypes: true }).filter(e => e.isDirectory()).map(e => e.name)
    : [];

  const libDir = path.join(WORKSPACE, "lib");
  const libSlugs: string[] = fs.existsSync(libDir)
    ? fs.readdirSync(libDir, { withFileTypes: true }).filter(e => e.isDirectory()).map(e => e.name)
    : [];

  const projectLines = artifactSlugs.map(slug => {
    const known = PROJECTS.find(p => p.slug === slug);
    const name = known?.name ?? slug.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase());
    const icon = known?.icon ?? "📦";
    const desc = known?.description ?? `Replit app — ${slug}`;
    return `| ${icon} [${name}](replit-apps/${slug}/) | ${desc} |`;
  }).join("\n");

  const libLines = libSlugs.map(slug => {
    const known = LIBS.find(p => p.slug === slug);
    const name = known?.name ?? slug.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase());
    const icon = known?.icon ?? "📚";
    const desc = known?.description ?? `Shared library — ${slug}`;
    return `| ${icon} [${name}](lib/${slug}/) | ${desc} |`;
  }).join("\n");

  const originalLines = ORIGINAL_FILES.map(p =>
    `| ${p.icon} [${p.name}](${p.slug === "termux-mp3" ? "Termux%20MP3%20player" : p.slug}) | ${p.description} |`
  ).join("\n");

  return [
    `# 🛰️ Alexandru- Distribution Hub`,
    ``,
    `> All projects built in Replit, automatically synced to GitHub.`,
    ``,
    `## Apps`,
    ``,
    `| Project | Description |`,
    `|---------|-------------|`,
    projectLines,
    ``,
    `## Shared Libraries`,
    ``,
    `| Library | Description |`,
    `|---------|-------------|`,
    libLines,
    ``,
    `## Original Files`,
    ``,
    `| File | Description |`,
    `|------|-------------|`,
    originalLines,
    ``,
    `---`,
    `*Synced automatically every 5 minutes by the GitHub Distribution Hub.*`,
  ].join("\n");
}

function collectFiles(): { path: string; content: string }[] {
  const files: { path: string; content: string }[] = [];

  // Root README
  files.push({ path: "README.md", content: generateRootReadme() });

  // Original cloned repo files
  const rootFiles = [
    { src: "cloned-repo/index.html", dest: "index.html" },
    { src: "cloned-repo/Termux MP3 player", dest: "Termux MP3 player" },
  ];
  for (const c of rootFiles) {
    const full = path.join(WORKSPACE, c.src);
    if (!fs.existsSync(full)) continue;
    try {
      const content = fs.readFileSync(full);
      if (content.length > 0) files.push({ path: c.dest, content: content.toString("utf8") });
    } catch { /* skip */ }
  }

  // Root workspace config files
  const rootConfigs = ["package.json", "pnpm-workspace.yaml", "tsconfig.json", "tsconfig.base.json", "replit.md"];
  for (const name of rootConfigs) {
    const full = path.join(WORKSPACE, name);
    if (!fs.existsSync(full)) continue;
    try {
      const content = fs.readFileSync(full);
      if (content.length > 0) files.push({ path: name, content: content.toString("utf8") });
    } catch { /* skip */ }
  }

  // Artifacts (apps)
  const artifactsDir = path.join(WORKSPACE, "artifacts");
  if (fs.existsSync(artifactsDir)) {
    const artifacts = fs.readdirSync(artifactsDir, { withFileTypes: true })
      .filter(e => e.isDirectory())
      .map(e => e.name);

    for (const artifact of artifacts) {
      files.push({ path: `replit-apps/${artifact}/README.md`, content: generateProjectReadme(artifact) });
      walkDir(path.join(artifactsDir, artifact), `replit-apps/${artifact}`, files);
    }
  }

  // Shared libraries (lib/)
  const libDir = path.join(WORKSPACE, "lib");
  if (fs.existsSync(libDir)) {
    const libs = fs.readdirSync(libDir, { withFileTypes: true })
      .filter(e => e.isDirectory())
      .map(e => e.name);

    for (const lib of libs) {
      files.push({ path: `lib/${lib}/README.md`, content: generateLibReadme(lib) });
      walkDir(path.join(libDir, lib), `lib/${lib}`, files);
    }
  }

  // Scripts
  const scriptsDir = path.join(WORKSPACE, "scripts", "src");
  if (fs.existsSync(scriptsDir)) {
    walkDir(scriptsDir, "scripts/src", files);
  }
  const scriptsPkg = path.join(WORKSPACE, "scripts", "package.json");
  if (fs.existsSync(scriptsPkg)) {
    try {
      const content = fs.readFileSync(scriptsPkg);
      if (content.length > 0) files.push({ path: "scripts/package.json", content: content.toString("utf8") });
    } catch { /* skip */ }
  }

  return files;
}

async function pushOne(
  file: SyncFile,
  connectors: ReplitConnectors,
  retries = 3
): Promise<{ file: string; status: string }> {
  // Use path segments — GitHub Contents API expects each segment encoded separately
  const urlPath = file.path.split("/").map(encodeURIComponent).join("/");
  const encoded = Buffer.isBuffer(file.content)
    ? file.content.toString("base64")
    : Buffer.from(file.content, "utf8").toString("base64");

  try {
    let sha: string | undefined;
    const existing = await connectors.proxy("github", `/repos/${OWNER}/${REPO}/contents/${urlPath}`, {
      method: "GET",
      headers: { Accept: "application/vnd.github+json" },
    });
    if (existing.ok) {
      const data = await existing.json() as { sha: string };
      sha = data.sha;
    }

    const body: Record<string, string> = {
      message: `Auto-push: ${file.path}`,
      content: encoded,
    };
    if (sha) body.sha = sha;

    const put = await connectors.proxy("github", `/repos/${OWNER}/${REPO}/contents/${urlPath}`, {
      method: "PUT",
      headers: {
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
      },
      body,
    });

    if (put.status === 409 && retries > 0) {
      // Wait longer on each retry to let GitHub settle
      await new Promise(r => setTimeout(r, 600 * (4 - retries)));
      return pushOne(file, connectors, retries - 1);
    }

    return { file: file.path, status: put.ok ? "pushed" : `failed (${put.status})` };
  } catch {
    return { file: file.path, status: "error" };
  }
}

async function pushFilesToGitHub(): Promise<{ file: string; status: string }[]> {
  const allFiles = collectFiles();
  const connectors = new ReplitConnectors();

  // Only push files whose content has changed since the last successful push
  const toUpdate = allFiles.filter(f => {
    const h = hashContent(f.content);
    if (pushedHashes.get(f.path) === h) return false;
    return true;
  });

  const skipped = allFiles.length - toUpdate.length;
  if (skipped > 0) logger.info({ skipped }, "Auto-push: skipping unchanged files");

  const results: { file: string; status: string }[] = [];
  for (const file of allFiles) {
    if (!toUpdate.includes(file)) {
      results.push({ file: file.path, status: "unchanged" });
    }
  }

  // Sequential writes — GitHub's Contents API conflicts on concurrent commits
  for (const file of toUpdate) {
    const result = await pushOne(file, connectors);
    results.push(result);
    if (result.status === "pushed") {
      pushedHashes.set(file.path, hashContent(file.content));
    }
  }

  return results;
}

export async function triggerPush(): Promise<void> {
  if (isPushing) {
    logger.info("Auto-push: already in progress, skipping");
    return;
  }
  isPushing = true;
  logger.info("Auto-push: starting");
  try {
    const results = await pushFilesToGitHub();
    lastPushTime = new Date();
    lastPushResults = results;
    const pushed = results.filter(r => r.status === "pushed").length;
    const failed = results.filter(r => r.status !== "pushed");
    logger.info({ pushed, total: results.length }, "Auto-push: complete");
    if (failed.length) logger.warn({ failed: failed.map(f => f.file) }, "Auto-push: failed files");
  } finally {
    isPushing = false;
  }
}

export function startAutoPush() {
  autoPushEnabled = true;
  logger.info({ intervalMs: PUSH_INTERVAL_MS }, "Auto-push: enabled through connected GitHub account");
  triggerPush().catch(e => logger.error({ err: e }, "Auto-push: startup push failed"));
  setInterval(() => {
    triggerPush().catch(e => logger.error({ err: e }, "Auto-push: scheduled push failed"));
  }, PUSH_INTERVAL_MS);
}
