import fs from "fs";
import path from "path";
import crypto from "crypto";
import { logger } from "./logger";
import { PROJECTS, ORIGINAL_FILES } from "./projects";

const WORKSPACE = "/home/runner/workspace";
const OWNER = "savinalexandru2002-prog";
const REPO = "Alexandru-";
const PUSH_INTERVAL_MS = 5 * 60 * 1000;

const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "build", ".cache", ".replit-artifact", "cloned-repo"]);
const ALLOWED_EXTS = new Set([".ts", ".js", ".tsx", ".jsx", ".json", ".yaml", ".yml", ".html", ".css", ".md", ".txt"]);

export let lastPushTime: Date | null = null;
export let lastPushResults: { file: string; status: string }[] = [];
export let autoPushEnabled = false;
export let isPushing = false;

// Track content hashes to skip unchanged files
const pushedHashes = new Map<string, string>();

function hashContent(content: string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

function walkDir(dir: string, base: string, results: { path: string; content: string }[]) {
  if (!fs.existsSync(dir)) return;
  let entries: fs.Dirent[];
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    const rel = path.posix.join(base, entry.name);
    if (entry.isDirectory()) {
      walkDir(full, rel, results);
    } else {
      if (!ALLOWED_EXTS.has(path.extname(entry.name))) continue;
      try {
        const content = fs.readFileSync(full, "utf8");
        if (content.trim().length > 0) results.push({ path: rel, content });
      } catch { /* skip binary */ }
    }
  }
}

function generateProjectReadme(slug: string): string {
  const meta = PROJECTS.find(p => p.slug === slug);
  const name = meta ? `${meta.icon} ${meta.name}` : slug;
  const desc = meta?.description ?? "A Replit project.";
  return [
    `# ${name}`,
    ``,
    `> ${desc}`,
    ``,
    `## About`,
    ``,
    `This project is part of the **Alexandru- Distribution Hub** — automatically synced from Replit every 5 minutes.`,
    ``,
    `## Structure`,
    ``,
    `| Path | Description |`,
    `|------|-------------|`,
    `| \`src/\` | Source code |`,
    `| \`index.html\` | Entry point (if applicable) |`,
    ``,
    `---`,
    `*Auto-generated by GitHub Distribution Hub*`,
  ].join("\n");
}

function generateRootReadme(): string {
  const projectLines = PROJECTS.map(p =>
    `| ${p.icon} [${p.name}](replit-apps/${p.slug}/) | ${p.description} |`
  ).join("\n");
  const originalLines = ORIGINAL_FILES.map(p =>
    `| ${p.icon} [${p.name}](${p.slug === "termux-mp3" ? "Termux MP3 player" : p.slug}) | ${p.description} |`
  ).join("\n");

  return [
    `# 🛰️ Alexandru- Distribution Hub`,
    ``,
    `> All projects built in Replit, automatically synced to GitHub.`,
    ``,
    `## Replit Apps`,
    ``,
    `| Project | Description |`,
    `|---------|-------------|`,
    projectLines,
    ``,
    `## Original Files`,
    ``,
    `| File | Description |`,
    `|------|-------------|`,
    originalLines,
    ``,
    `---`,
    `*Synced automatically every 5 minutes by the GitHub Distribution Hub.*`,
  ].join("\n");
}

function collectFiles(): { path: string; content: string }[] {
  const files: { path: string; content: string }[] = [];

  // Root README
  files.push({ path: "README.md", content: generateRootReadme() });

  // Original cloned repo files
  const rootFiles = [
    { src: "cloned-repo/index.html", dest: "index.html" },
    { src: "cloned-repo/Termux MP3 player", dest: "Termux MP3 player" },
  ];
  for (const c of rootFiles) {
    const full = path.join(WORKSPACE, c.src);
    if (!fs.existsSync(full)) continue;
    try {
      const content = fs.readFileSync(full, "utf8");
      if (content.trim().length > 0) files.push({ path: c.dest, content });
    } catch { /* skip */ }
  }

  const artifactsDir = path.join(WORKSPACE, "artifacts");
  if (fs.existsSync(artifactsDir)) {
    const artifacts = fs.readdirSync(artifactsDir, { withFileTypes: true })
      .filter(e => e.isDirectory())
      .map(e => e.name);

    for (const artifact of artifacts) {
      const srcDir = path.join(artifactsDir, artifact, "src");
      const indexHtml = path.join(artifactsDir, artifact, "index.html");

      // Per-project README
      files.push({ path: `replit-apps/${artifact}/README.md`, content: generateProjectReadme(artifact) });

      walkDir(srcDir, `replit-apps/${artifact}/src`, files);
      if (fs.existsSync(indexHtml)) {
        try {
          const content = fs.readFileSync(indexHtml, "utf8");
          if (content.trim().length > 0) files.push({ path: `replit-apps/${artifact}/index.html`, content });
        } catch { /* skip */ }
      }
    }
  }

  return files;
}

async function pushOne(
  file: { path: string; content: string },
  headers: Record<string, string>,
  retries = 3
): Promise<{ file: string; status: string }> {
  // Use path segments — GitHub Contents API expects each segment encoded separately
  const urlPath = file.path.split("/").map(encodeURIComponent).join("/");
  const apiUrl = `https://api.github.com/repos/${OWNER}/${REPO}/contents/${urlPath}`;
  const encoded = Buffer.from(file.content, "utf8").toString("base64");

  try {
    let sha: string | undefined;
    const existing = await fetch(apiUrl, { headers });
    if (existing.ok) {
      const data = await existing.json() as { sha: string };
      sha = data.sha;
    }

    const body: Record<string, string> = {
      message: `Auto-push: ${file.path}`,
      content: encoded,
    };
    if (sha) body.sha = sha;

    const put = await fetch(apiUrl, { method: "PUT", headers, body: JSON.stringify(body) });

    if (put.status === 409 && retries > 0) {
      // Wait longer on each retry to let GitHub settle
      await new Promise(r => setTimeout(r, 600 * (4 - retries)));
      return pushOne(file, headers, retries - 1);
    }

    return { file: file.path, status: put.ok ? "pushed" : `failed (${put.status})` };
  } catch {
    return { file: file.path, status: "error" };
  }
}

async function pushFilesToGitHub(token: string): Promise<{ file: string; status: string }[]> {
  const allFiles = collectFiles();
  const headers: Record<string, string> = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
  };

  // Only push files whose content has changed since the last successful push
  const toUpdate = allFiles.filter(f => {
    const h = hashContent(f.content);
    if (pushedHashes.get(f.path) === h) return false;
    return true;
  });

  const skipped = allFiles.length - toUpdate.length;
  if (skipped > 0) logger.info({ skipped }, "Auto-push: skipping unchanged files");

  const results: { file: string; status: string }[] = [];

  // Sequential writes — GitHub's Contents API conflicts on concurrent commits
  for (const file of toUpdate) {
    const result = await pushOne(file, headers);
    results.push(result);
    if (result.status === "pushed") {
      pushedHashes.set(file.path, hashContent(file.content));
    }
  }

  return results;
}

export async function triggerPush(): Promise<void> {
  if (isPushing) {
    logger.info("Auto-push: already in progress, skipping");
    return;
  }
  const token = process.env.GITHUB_PERSONAL_ACCESS_TOKEN;
  if (!token) {
    logger.warn("Auto-push skipped: GITHUB_PERSONAL_ACCESS_TOKEN not set");
    return;
  }
  isPushing = true;
  logger.info("Auto-push: starting");
  try {
    const results = await pushFilesToGitHub(token);
    lastPushTime = new Date();
    lastPushResults = results;
    const pushed = results.filter(r => r.status === "pushed").length;
    const failed = results.filter(r => r.status !== "pushed");
    logger.info({ pushed, total: results.length }, "Auto-push: complete");
    if (failed.length) logger.warn({ failed: failed.map(f => f.file) }, "Auto-push: failed files");
  } finally {
    isPushing = false;
  }
}

export function startAutoPush() {
  const token = process.env.GITHUB_PERSONAL_ACCESS_TOKEN;
  if (!token) {
    logger.warn("Auto-push disabled: GITHUB_PERSONAL_ACCESS_TOKEN not set");
    return;
  }
  autoPushEnabled = true;
  logger.info({ intervalMs: PUSH_INTERVAL_MS }, "Auto-push: enabled");
  triggerPush().catch(e => logger.error({ err: e }, "Auto-push: startup push failed"));
  setInterval(() => {
    triggerPush().catch(e => logger.error({ err: e }, "Auto-push: scheduled push failed"));
  }, PUSH_INTERVAL_MS);
}
