import fs from "fs";
import path from "path";
import crypto from "crypto";
import { logger } from "./logger";
import { PROJECTS, LIBS, ORIGINAL_FILES } from "./projects";
import { ReplitConnectors } from "@replit/connectors-sdk";

const WORKSPACE = "/home/runner/workspace";
const OWNER = "savinalexandru2002-prog";
const REPO = "Alexandru-";
const PUSH_INTERVAL_MS = 5 * 60 * 1000;

const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  ".cache",
  ".replit-artifact",
  "cloned-repo",
  ".turbo",
  ".vite",
]);
const ALLOWED_EXTS = new Set([
  ".ts", ".js", ".tsx", ".jsx", ".mjs", ".cjs",
  ".json", ".yaml", ".yml", ".toml",
  ".html", ".css", ".scss", ".md", ".txt",
  ".svg", ".webmanifest", ".ico",
  ".py", ".sh", ".sql",
]);

export let lastPushTime: Date | null = null;
export let lastPushResults: { file: string; status: string }[] = [];
export let autoPushEnabled = false;
export let isPushing = false;

// Track content hashes to skip unchanged files
const pushedHashes = new Map<string, string>();

type SyncFile = { path: string; content: Buffer | string };

function hashContent(content: Buffer | string): string {
  return crypto.createHash("sha256").update(content).digest("hex");
}

function walkDir(dir: string, base: string, results: SyncFile[]) {
  if (!fs.existsSync(dir)) return;
  let entries: fs.Dirent[];
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return; }
  for (const entry of entries) {
    if (SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    const rel = path.posix.join(base, entry.name);
    if (entry.isDirectory()) {
      walkDir(full, rel, results);
    } else {
      if (!ALLOWED_EXTS.has(path.extname(entry.name))) continue;
      try {
        const content = fs.readFileSync(full);
        if (content.length > 0) {
          results.push({ path: rel, content: isTextFile(entry.name) ? content.toString("utf8") : content });
        }
      } catch { /* skip binary */ }
    }
  }
}

function isTextFile(name: string): boolean {
  return ![".ico"].includes(path.extname(name).toLowerCase());
}

function generateProjectReadme(slug: string): string {
  const meta = PROJECTS.find(p => p.slug === slug);
  const name = meta ? `${meta.icon} ${meta.name}` : slug;
  const desc = meta?.description ?? "A Replit project.";
  return [
    `# ${name}`,
    ``,
    `> ${desc}`,
    ``,
    `## About`,
    ``,
    `This project is part of the **Alexandru- Distribution Hub** — automatically synced from Replit every 5 minutes.`,
    ``,
    `## Structure`,
    ``,
    `| Path | Description |`,
    `|------|-------------|`,
    `| \`src/\` | Source code |`,
    `| \`index.html\` | Entry point (if applicable) |`,
    ``,
    `---`,
    `*Auto-generated by GitHub Distribution Hub*`,
  ].join("\n");
}

function generateLibReadme(slug: string): string {
  const meta = LIBS.find(p => p.slug === slug);
  const name = meta ? `${meta.icon} ${meta.name}` : slug;
  const desc = meta?.description ?? "A shared library.";
  return [
    `# ${name}`,
    ``,
    `> ${desc}`,
    ``,
    `## About`,
    ``,
    `This is a shared library used across the **Alexandru- Distribution Hub** projects. Automatically synced from Replit.`,
    ``,
    `---`,
    `*Auto-generated by GitHub Distribution Hub*`,
  ].join("\n");
}

function generateRootReadme(): string {
  // Discover artifacts dynamically
  const artifactsDir = path.join(WORKSPACE, "artifacts");
  const artifactSlugs: string[] = fs.existsSync(artifactsDir)
    ? fs.readdirSync(artifactsDir, { withFileTypes: true }).filter(e => e.isDirectory()).map(e => e.name)
    : [];

  const libDir = path.join(WORKSPACE, "lib");
  const libSlugs: string[] = fs.existsSync(libDir)
    ? fs.readdirSync(libDir, { withFileTypes: true }).filter(e => e.isDirectory()).map(e => e.name)
    : [];

  const projectLines = artifactSlugs.map(slug => {
    const known = PROJECTS.find(p => p.slug === slug);
    const name = known?.name ?? slug.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase());
    const icon = known?.icon ?? "📦";
    const desc = known?.description ?? `Replit app — ${slug}`;
    return `| ${icon} [${name}](replit-apps/${slug}/) | ${desc} |`;
  }).join("\n");

  const libLines = libSlugs.map(slug => {
    const known = LIBS.find(p => p.slug === slug);
    const name = known?.name ?? slug.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase());
    const icon = known?.icon ?? "📚";
    const desc = known?.description ?? `Shared library — ${slug}`;
    return `| ${icon} [${name}](lib/${slug}/) | ${desc} |`;
  }).join("\n");

  const originalLines = ORIGINAL_FILES.map(p =>
    `| ${p.icon} [${p.name}](${p.slug === "termux-mp3" ? "Termux%20MP3%20player" : p.slug}) | ${p.description} |`
  ).join("\n");

  return [
    `# 🛰️ Alexandru- Distribution Hub`,
    ``,
    `> All projects built in Replit, automatically synced to GitHub.`,
    ``,
    `## Apps`,
    ``,
    `| Project | Description |`,
    `|---------|-------------|`,
    projectLines,
    ``,
    `## Shared Libraries`,
    ``,
    `| Library | Description |`,
    `|---------|-------------|`,
    libLines,
    ``,
    `## Original Files`,
    ``,
    `| File | Description |`,
    `|------|-------------|`,
    originalLines,
    ``,
    `---`,
    `*Synced automatically every 5 minutes by the GitHub Distribution Hub.*`,
  ].join("\n");
}

function collectFiles(): { path: string; content: string }[] {
  const files: { path: string; content: string }[] = [];

  // Root README
  files.push({ path: "README.md", content: generateRootReadme() });

  // Original cloned repo files
  const rootFiles = [
    { src: "cloned-repo/index.html", dest: "index.html" },
    { src: "cloned-repo/Termux MP3 player", dest: "Termux MP3 player" },
  ];
  for (const c of rootFiles) {
    const full = path.join(WORKSPACE, c.src);
    if (!fs.existsSync(full)) continue;
    try {
      const content = fs.readFileSync(full);
      if (content.length > 0) files.push({ path: c.dest, content: content.toString("utf8") });
    } catch { /* skip */ }
  }

  // Root workspace config files
  const rootConfigs = ["package.json", "pnpm-workspace.yaml", "tsconfig.json", "tsconfig.base.json", "replit.md"];
  for (const name of rootConfigs) {
    const full = path.join(WORKSPACE, name);
    if (!fs.existsSync(full)) continue;
    try {
      const content = fs.readFileSync(full);
      if (content.length > 0) files.push({ path: name, content: content.toString("utf8") });
    } catch { /* skip */ }
  }

  // Artifacts (apps)
  const artifactsDir = path.join(WORKSPACE, "artifacts");
  if (fs.existsSync(artifactsDir)) {
    const artifacts = fs.readdirSync(artifactsDir, { withFileTypes: true })
      .filter(e => e.isDirectory())
      .map(e => e.name);

    for (const artifact of artifacts) {
      files.push({ path: `replit-apps/${artifact}/README.md`, content: generateProjectReadme(artifact) });
      walkDir(path.join(artifactsDir, artifact), `replit-apps/${artifact}`, files);
    }
  }

  // Shared libraries (lib/)
  const libDir = path.join(WORKSPACE, "lib");
  if (fs.existsSync(libDir)) {
    const libs = fs.readdirSync(libDir, { withFileTypes: true })
      .filter(e => e.isDirectory())
      .map(e => e.name);

    for (const lib of libs) {
      files.push({ path: `lib/${lib}/README.md`, content: generateLibReadme(lib) });
      walkDir(path.join(libDir, lib), `lib/${lib}`, files);
    }
  }

  // Scripts
  const scriptsDir = path.join(WORKSPACE, "scripts", "src");
  if (fs.existsSync(scriptsDir)) {
    walkDir(scriptsDir, "scripts/src", files);
  }
  const scriptsPkg = path.join(WORKSPACE, "scripts", "package.json");
  if (fs.existsSync(scriptsPkg)) {
    try {
      const content = fs.readFileSync(scriptsPkg);
      if (content.length > 0) files.push({ path: "scripts/package.json", content: content.toString("utf8") });
    } catch { /* skip */ }
  }

  return files;
}

async function pushFilesToGitHub(): Promise<{ file: string; status: string }[]> {
  const allFiles = collectFiles();
  const connectors = new ReplitConnectors();

  // Only push files whose content has changed since the last successful push
  const toUpdate = allFiles.filter(f => {
    const h = hashContent(f.content);
    if (pushedHashes.get(f.path) === h) return false;
    return true;
  });

  const skipped = allFiles.length - toUpdate.length;
  if (skipped > 0) logger.info({ skipped }, "Auto-push: skipping unchanged files");

  const results: { file: string; status: string }[] = [];
  for (const file of allFiles) {
    if (!toUpdate.includes(file)) {
      results.push({ file: file.path, status: "unchanged" });
    }
  }

  if (toUpdate.length === 0) return results;

  const api = `/repos/${OWNER}/${REPO}`;
  const headers = {
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
  };
  async function githubRequest(
    requestPath: string,
    options: { method: string; headers: Record<string, string>; body?: unknown },
  ): Promise<Response> {
    for (let attempt = 0; attempt < 5; attempt++) {
      const response = await connectors.proxy("github", requestPath, options);
      if (response.status !== 429 && response.status < 500) return response;
      const retryAfter = Number(response.headers.get("retry-after") ?? "0");
      const waitMs = retryAfter > 0 ? retryAfter * 1000 : 1000 * (attempt + 1);
      logger.warn({ status: response.status, waitMs }, "Auto-push: GitHub asked for a retry");
      await new Promise(resolve => setTimeout(resolve, waitMs));
    }
    return connectors.proxy("github", requestPath, options);
  }

  try {
    // Build blobs in parallel, then publish one atomic tree/commit. This avoids
    // the Contents API's one-commit-per-file race and partial uploads.
    const blobResults: { file: SyncFile; sha?: string; error?: string }[] = [];
    for (let i = 0; i < toUpdate.length; i += 5) {
      const batch = toUpdate.slice(i, i + 5);
      const created = await Promise.all(batch.map(async (file) => {
        const content = Buffer.isBuffer(file.content)
          ? file.content.toString("base64")
          : Buffer.from(file.content, "utf8").toString("base64");
        const response = await githubRequest(`${api}/git/blobs`, {
          method: "POST",
          headers,
          body: { content, encoding: "base64" },
        });
        if (!response.ok) return { file, error: `failed (${response.status})` };
        const data = await response.json() as { sha?: string };
        return data.sha ? { file, sha: data.sha } : { file, error: "error" };
      }));
      blobResults.push(...created);
    }

    const blobFailures = blobResults.filter(item => !item.sha);
    if (blobFailures.length > 0) {
      return [
        ...results,
        ...blobResults.map(item => ({ file: item.file.path, status: item.error ?? "error" })),
      ];
    }

    const refResponse = await githubRequest(`${api}/git/ref/heads/main`, {
      method: "GET",
      headers,
    });
    if (!refResponse.ok) throw new Error(`Could not read main branch (${refResponse.status})`);
    const ref = await refResponse.json() as { object?: { sha?: string } };
    const parentSha = ref.object?.sha;
    if (!parentSha) throw new Error("GitHub did not return the main branch SHA");

    const commitResponse = await githubRequest(`${api}/git/commits/${parentSha}`, {
      method: "GET",
      headers,
    });
    if (!commitResponse.ok) throw new Error(`Could not read repository tree (${commitResponse.status})`);
    const commit = await commitResponse.json() as { tree?: { sha?: string } };
    const baseTreeSha = commit.tree?.sha;
    if (!baseTreeSha) throw new Error("GitHub did not return the repository tree SHA");

    const treeResponse = await githubRequest(`${api}/git/trees`, {
      method: "POST",
      headers,
      body: {
        base_tree: baseTreeSha,
        tree: blobResults.map(item => ({
          path: item.file.path,
          mode: "100644",
          type: "blob",
          sha: item.sha,
        })),
      },
    });
    if (!treeResponse.ok) throw new Error(`Could not create repository tree (${treeResponse.status})`);
    const tree = await treeResponse.json() as { sha?: string };
    if (!tree.sha) throw new Error("GitHub did not return the new tree SHA");

    const newCommitResponse = await githubRequest(`${api}/git/commits`, {
      method: "POST",
      headers,
      body: {
        message: `Auto-publish ${toUpdate.length} changed project files`,
        tree: tree.sha,
        parents: [parentSha],
      },
    });
    if (!newCommitResponse.ok) throw new Error(`Could not create commit (${newCommitResponse.status})`);
    const newCommit = await newCommitResponse.json() as { sha?: string };
    if (!newCommit.sha) throw new Error("GitHub did not return the new commit SHA");

    const updateRefResponse = await githubRequest(`${api}/git/refs/heads/main`, {
      method: "PATCH",
      headers,
      body: { sha: newCommit.sha, force: false },
    });
    if (!updateRefResponse.ok) throw new Error(`Could not publish commit (${updateRefResponse.status})`);

    for (const item of blobResults) {
      pushedHashes.set(item.file.path, hashContent(item.file.content));
      results.push({ file: item.file.path, status: "pushed" });
    }
  } catch (error) {
    logger.error({ err: error }, "Auto-push: atomic publish failed");
    for (const file of toUpdate) {
      results.push({ file: file.path, status: "error" });
    }
  }

  return results;
}

export async function triggerPush(): Promise<void> {
  if (isPushing) {
    logger.info("Auto-push: already in progress, skipping");
    return;
  }
  isPushing = true;
  logger.info("Auto-push: starting");
  try {
    const results = await pushFilesToGitHub();
    lastPushTime = new Date();
    lastPushResults = results;
    const pushed = results.filter(r => r.status === "pushed").length;
    const failed = results.filter(r => r.status !== "pushed");
    logger.info({ pushed, total: results.length }, "Auto-push: complete");
    if (failed.length) logger.warn({ failed: failed.map(f => f.file) }, "Auto-push: failed files");
  } finally {
    isPushing = false;
  }
}

export function startAutoPush() {
  autoPushEnabled = true;
  logger.info({ intervalMs: PUSH_INTERVAL_MS }, "Auto-push: enabled through connected GitHub account");
  triggerPush().catch(e => logger.error({ err: e }, "Auto-push: startup push failed"));
  setInterval(() => {
    triggerPush().catch(e => logger.error({ err: e }, "Auto-push: scheduled push failed"));
  }, PUSH_INTERVAL_MS);
}
